### ISSUE TITLE
Why I can't upload to the firebase on android using your branch <0.10.9> 

### ISSUE THREAD

**Issue by rhenmark** [lll000111/react-native-fetch-blob#3]
Hi ! Thank you for reporting an issue, but we would like to remind you, we have a trouble shooting page in our wiki. 
You may want to take a look on that page or find issues tagged "trouble shooting" :p 

* please provide the version of installed library and RN project.
* a sample code snippet/repository is very helpful to spotting the problem.
* issues which have been tagged as 'needs feedback', will be closed after 2 weeks if receive no feedbacks.
* issues lack of detailed information will be closed without any feedback

**Comment by rhenmark** [comment]
Im stack up on uploading but no error or success return when uploading in firebase.

**Comment by rhenmark** [comment]
+ 1

**Comment by rhenmark** [comment]
+1

**Comment by rhenmark** [comment]
+1

**Comment by lll000111** [comment]
I'm not taking issues on this folked repo, pls. report in the original one. This is just for my development and my own needs. I'm not otherwise interested in RNFB, I just happen to need the filesystem part of it for my own stuff.

**Comment by lll000111** [comment]
Besides, I can only do anything on Android since I don't own any Apple hardware.

**Comment by lll000111** [comment]
You may be better off asking on StackOverflow, the owner of RNFB is overwhelmed by the demands of fixing lots of issues for lots of people for free &mdash; like most open source Github projects.

**Comment by rhenmark** [comment]
the apple is working though, while android don't. Do you have any idea?

**Comment by lll000111** [comment]
No. I only use a few of the the filesystem functions. I don't even know (or care) what Firebase even is.

**Comment by rhenmark** [comment]
Okay, but thanks
